Repository pgjdbc/r2dbc-postgresql, pull requests merged in 2019-09, with the labels that each got.

#141 Fixed rollback behavior in case of transaction status OPEN or FAILED
  src/main/java/io/r2dbc/postgresql/PostgresqlConnection.java
  src/test/java/io/r2dbc/postgresql/PostgresqlConnectionTest.java
Labels: type: bug

#114 Avoid array index out of bounds on missing result size in tag
  src/main/java/io/r2dbc/postgresql/message/backend/CommandComplete.java
  src/test/java/io/r2dbc/postgresql/message/backend/CommandCompleteTest.java
Labels: type: bug

#127 Mockito 3.0.0
  pom.xml
Labels: type: dependency-upgrade

#161 Implement JSON and JSONB codecs
  .gitignore
  README.md
  src/main/java/io/r2dbc/postgresql/codec/DefaultCodecs.java
  src/main/java/io/r2dbc/postgresql/codec/JsonCodec.java
  src/main/java/io/r2dbc/postgresql/codec/JsonbCodec.java
  src/main/java/io/r2dbc/postgresql/type/PostgresqlObjectId.java
  src/test/java/io/r2dbc/postgresql/codec/CodecIntegrationTest.java
  src/test/java/io/r2dbc/postgresql/codec/DefaultCodecsTest.java
  src/test/java/io/r2dbc/postgresql/codec/JsonCodecTest.java
  src/test/java/io/r2dbc/postgresql/codec/JsonbCodecTest.java
Labels: type: enhancement

#174 Added documentation for options parameter in ConnectionConfiguration
  README.md
Labels: type: documentation
